version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: inlaze_movies
      POSTGRES_USER: inlaze
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
